config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :stories
  resources :categories
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:email, :given_name, :family_name, :nickname, :unverified_email, :status, :encrypted_password, :password_expires_at, :daily_alerts, :daily_alerts_at, :login_attempts, :max_login_attempts, :start_online_at, :finish_online_at, :auto_online, :birthday, :photo, :cashback, :credit, :starts, :max_starts, :notes)
    end
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :account_email %>
  </div>

  <div class="field">
    <%= form.label :given_name %>
    <%= form.text_field :given_name, id: :account_given_name %>
  </div>

  <div class="field">
    <%= form.label :family_name %>
    <%= form.text_field :family_name, id: :account_family_name %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :account_nickname %>
  </div>

  <div class="field">
    <%= form.label :unverified_email %>
    <%= form.check_box :unverified_email, id: :account_unverified_email %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :account_status %>
  </div>

  <div class="field">
    <%= form.label :encrypted_password %>
    <%= form.text_field :encrypted_password, id: :account_encrypted_password %>
  </div>

  <div class="field">
    <%= form.label :password_expires_at %>
    <%= form.datetime_select :password_expires_at, id: :account_password_expires_at %>
  </div>

  <div class="field">
    <%= form.label :daily_alerts %>
    <%= form.check_box :daily_alerts, id: :account_daily_alerts %>
  </div>

  <div class="field">
    <%= form.label :daily_alerts_at %>
    <%= form.time_select :daily_alerts_at, id: :account_daily_alerts_at %>
  </div>

  <div class="field">
    <%= form.label :login_attempts %>
    <%= form.number_field :login_attempts, id: :account_login_attempts %>
  </div>

  <div class="field">
    <%= form.label :max_login_attempts %>
    <%= form.number_field :max_login_attempts, id: :account_max_login_attempts %>
  </div>

  <div class="field">
    <%= form.label :start_online_at %>
    <%= form.time_select :start_online_at, id: :account_start_online_at %>
  </div>

  <div class="field">
    <%= form.label :finish_online_at %>
    <%= form.time_select :finish_online_at, id: :account_finish_online_at %>
  </div>

  <div class="field">
    <%= form.label :auto_online %>
    <%= form.check_box :auto_online, id: :account_auto_online %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :account_birthday %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :account_photo %>
  </div>

  <div class="field">
    <%= form.label :cashback %>
    <%= form.text_field :cashback, id: :account_cashback %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.text_field :credit, id: :account_credit %>
  </div>

  <div class="field">
    <%= form.label :starts %>
    <%= form.text_field :starts, id: :account_starts %>
  </div>

  <div class="field">
    <%= form.label :max_starts %>
    <%= form.text_field :max_starts, id: :account_max_starts %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :account_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Given name</th>
      <th>Family name</th>
      <th>Nickname</th>
      <th>Unverified email</th>
      <th>Status</th>
      <th>Encrypted password</th>
      <th>Password expires at</th>
      <th>Daily alerts</th>
      <th>Daily alerts at</th>
      <th>Login attempts</th>
      <th>Max login attempts</th>
      <th>Start online at</th>
      <th>Finish online at</th>
      <th>Auto online</th>
      <th>Birthday</th>
      <th>Photo</th>
      <th>Cashback</th>
      <th>Credit</th>
      <th>Starts</th>
      <th>Max starts</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.email %></td>
        <td><%= account.given_name %></td>
        <td><%= account.family_name %></td>
        <td><%= account.nickname %></td>
        <td><%= account.unverified_email %></td>
        <td><%= account.status %></td>
        <td><%= account.encrypted_password %></td>
        <td><%= account.password_expires_at %></td>
        <td><%= account.daily_alerts %></td>
        <td><%= account.daily_alerts_at %></td>
        <td><%= account.login_attempts %></td>
        <td><%= account.max_login_attempts %></td>
        <td><%= account.start_online_at %></td>
        <td><%= account.finish_online_at %></td>
        <td><%= account.auto_online %></td>
        <td><%= account.birthday %></td>
        <td><%= account.photo %></td>
        <td><%= account.cashback %></td>
        <td><%= account.credit %></td>
        <td><%= account.starts %></td>
        <td><%= account.max_starts %></td>
        <td><%= account.notes %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Given name:</strong>
  <%= @account.given_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @account.family_name %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @account.nickname %>
</p>

<p>
  <strong>Unverified email:</strong>
  <%= @account.unverified_email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @account.encrypted_password %>
</p>

<p>
  <strong>Password expires at:</strong>
  <%= @account.password_expires_at %>
</p>

<p>
  <strong>Daily alerts:</strong>
  <%= @account.daily_alerts %>
</p>

<p>
  <strong>Daily alerts at:</strong>
  <%= @account.daily_alerts_at %>
</p>

<p>
  <strong>Login attempts:</strong>
  <%= @account.login_attempts %>
</p>

<p>
  <strong>Max login attempts:</strong>
  <%= @account.max_login_attempts %>
</p>

<p>
  <strong>Start online at:</strong>
  <%= @account.start_online_at %>
</p>

<p>
  <strong>Finish online at:</strong>
  <%= @account.finish_online_at %>
</p>

<p>
  <strong>Auto online:</strong>
  <%= @account.auto_online %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @account.birthday %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @account.photo %>
</p>

<p>
  <strong>Cashback:</strong>
  <%= @account.cashback %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @account.credit %>
</p>

<p>
  <strong>Starts:</strong>
  <%= @account.starts %>
</p>

<p>
  <strong>Max starts:</strong>
  <%= @account.max_starts %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @account.notes %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>